### ISSUE TITLE
Critical BN bug on Realms when displaying large veHNT position after multiplier bonus

### ISSUE THREAD

**Issue by shupcode** [helium/helium-program-library#206]
We hold a large veHNT position and when using realms we hit a UI error when the position is being displayed.

In Chrome Debugging:
```javascript
        const g = e=>{
            let {position: t, registrar: n} = e
              , o = new s.BN(0);
            const r = (null === n || void 0 === n ? void 0 : n.votingMints) || []
              , i = t ? r[t.votingMintConfigIdx] : void 0;
            if (t && i) {
                const {lockupSaturationSecs: e, baselineVoteWeightScaledFactor: n, maxExtraLockupVoteWeightScaledFactor: r, genesisVotePowerMultiplier: a=1} = i
                  , c = new s.BN(Math.round((new Date).getTime() / 1e3))
                  , u = t.genesisEnd.gt(c)
                  , l = t.lockup
                  , d = "constant" === Object.keys(l.kind)[0] ? l.startTs : c
                  , m = l.endTs.sub(d).toNumber()
                  , p = t.amountDepositedNative.toNumber()
                  , g = n.toNumber()
                  , f = r.toNumber()
                  , y = e.toNumber()
                  , b = (u ? a : 1) * (0,
                h.$)({
                    baselineScaledFactor: g,
                    maxExtraLockupScaledFactor: f,
                    lockupSecs: m,
                    lockupSaturationSecs: y
                });
                o = new s.BN(p * b)
```
The error happens on the last line:
```javascript
o = new s.BN(p * b)
```

I am guessing the correct implementation should be
```javascript
o = new s.BN(p).mul(new s.BN(b))
```

**Comment by shupcode** [comment]
Please help as we cannot stake with the subDAOs or do anything with our position until this is fixed.

**Comment by bryzettler** [comment]
@shupcode thanks for bringing this to our attention, the fix has been deployed

**Comment by shupcode** [comment]
> @shupcode thanks for bringing this to our attention, the fix has been deployed

@bryzettler thanks for fast response.

It looks like we ran into another issue. For context we hold a 6 digit hnt position locked for 4 years. the resulting veHNT position went beyond 53 bits?

We are now getting this error on the page:

```
Something went wrong.
Number can only safely store up to 53 bits
Refresh and try again
Error: Number can only safely store up to 53 bits at o (https://realms.heliumvote.com/_next/static/chunks/pages/_app-31825e44e9607aeb.js:356:8814432) at i.toNumber (https://realms.heliumvote.com/_next/static/chunks/pages/_app-31825e44e9607aeb.js:356:8820166) at Ce (https://realms.heliumvote.com/_next/static/chunks/pages/dao/%5Bsymbol%5D/account/%5BtokenOwnerRecordPk%5D-9051088f42aa8499.js:1:44666) at go (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:62699) at di (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:120091) at is (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:106944) at os (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:106872) at as (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:106735) at Ki (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:103532) at qi (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:102098)Something went wrong.
Number can only safely store up to 53 bits
Refresh and try again
Error: Number can only safely store up to 53 bits at o (https://realms.heliumvote.com/_next/static/chunks/pages/_app-31825e44e9607aeb.js:356:8814432) at i.toNumber (https://realms.heliumvote.com/_next/static/chunks/pages/_app-31825e44e9607aeb.js:356:8820166) at Ce (https://realms.heliumvote.com/_next/static/chunks/pages/dao/%5Bsymbol%5D/account/%5BtokenOwnerRecordPk%5D-9051088f42aa8499.js:1:44666) at go (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:62699) at di (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:120091) at is (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:106944) at os (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:106872) at as (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:106735) at Ki (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:103532) at qi (https://realms.heliumvote.com/_next/static/chunks/framework-bb32ab2dd91f6b58.js:1:102098)
```

**Comment by shupcode** [comment]
@bryzettler 

The error occured on thie last line ```when calling r.votingPower.toNumber()
``` in the chrome debugger:

```javascript
S.BX)("div", {
                        className: "p-4 rounded-lg flex flex-col h-full w-full",
                        style: {
                            minHeight: "260px"
                        },
                        children: [(0,
                        S.BX)("div", {
                            className: "flex flex-wrap mb-4",
                            children: [(0,
                            S.tZ)(He, {
                                label: "Lockup Type",
                                value: We
                            }), Ae && (0,
                            S.tZ)(He, {
                                label: "Vote Multiplier",
                                value: ((r.votingPower.isZero() ? 0 : r.votingPower.toNumber() / r.amountDepositedNative.toNumber()) / (r.genesisEnd.gt(new f.BN(d)) ? Ve.genesisVotePowerMultiplier : 1)).toFixed(2)
                                
                               
```
